### ISSUE TITLE
RubyMotion version

### ISSUE THREAD

**Issue by brunodp** [raywenderlich/SKTUtils#18]
Hi !

This is not an issue. I didn't know where else to contact you to tell you that I've translated SKTUtils and the demo to RubyMotion. Let me know if you're interested in adding a RM branch. SKTUtils are awesome, thanks a lot.

Best,

Bruno.

**Comment by icanzilb** [comment]
Thanks and sorry for not having a look at this earlier, we haven't got much RubyMotion materials at raywenderlich.com as we focus primarily on Swift for our iOS tutorials. Thanks for bringing the lib to the RubyMotion community
