### ISSUE TITLE
I made a ring chart library that relies on this project

### ISSUE THREAD

**Issue by benmorrow** [raywenderlich/SKTUtils#24]
Hi,

This is more of an announcement than an issue. I made a ring chart library named [SKTRings](https://github.com/happywatch/SKTRings) that builds upon the tools in SKTUtils. The rings animate using SKTEffects:

![iOS, watchOS animated rings with SpriteKit](https://media.giphy.com/media/32oaBkqWFqfAc/giphy.gif)

**Comment by icanzilb** [comment]
Hey Ben, this looks real cool! I'll ping Ray and send a tweet out 👍
